platform:
- x64
environment:
  nodejs_version: "12"
cache:
- '%APPDATA%\npm-cache'
- '%APPDATA%\Yarn'
- '%USERPROFILE%\.electron'
- node_modules
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\yarn;%PATH%
- yarn install

test_script:
- node --version
- npm --version
- yarn --version
- yarn run lint
- if %APPVEYOR_REPO_TAG% EQU false yarn make

build_script:
- IF %APPVEYOR_REPO_TAG% EQU true yarn release

build:
  publish_wap: true
  verbosity: minimal

deploy:
  release: product release of VICREO
  description: ''
  provider: GitHub
  auth_token:
    secure: QHN3cMjhdFlzAJorXZXnE0smUAC8K+VCm5lyB/L7Zwe+ADZc7JdxKkDBF/NDZPQ6
  draft: true
  prerelease: false
  Force update: true
  on:
    branch: master