language: node_js
node_js: "10"
os:
- linux
- osx
dist: bionic
osx_image: xcode10.1

cache:
  npm: true
  yarn: true
  directories:
  - $HOME/.cache/electron

addons:
  apt:
    packages:
    - fakeroot
    - rpm
    - libxtst-dev
    - libpng++-dev

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/

script:
- npm run release