{
  "language": "ruby",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "branches": {
    "except": [
      "/^v\\d+\\.\\d+\\.\\d+$/"
    ]
  },
  "env": [
    "global={:ELECTRON_CACHE=>\"$HOME/.cache/electron\"}={:ELECTRON_BUILDER_CACHE=>\"$HOME/.cache/electron-builder\"}"
  ],
  "cache": {
    "directories": [
      "node_modules",
      "$HOME/.cache/electron",
      "$HOME/.cache/electron-builder"
    ]
  },
  "before_cache": [
    "rm -rf $HOME/.cache/electron-builder/wine"
  ],
  "before_install": [
    "if [ \"$TRAVIS_OS_NAME\" == \"linux\" ]; then sudo apt-get install libxtst-dev libpng++-dev; fi"
  ],
  "script": [
    "if [ \"$TRAVIS_OS_NAME\" == \"linux\" ]; then\n  docker run --rm \\\n    -v ${PWD}:/project \\\n    -v ~/.cache/electron:/root/.cache/electron \\\n    -v ~/.cache/electron-builder:/root/.cache/electron-builder \\\n    electronuserland/builder:wine \\\n    /bin/bash -c \"yarn --link-duplicates --pure-lockfile && yarn release --linux --win\"\nelse\n  yarn release\nfi\n"
  ],
  "jobs": {
    "include": [
      {
        "os": "osx",
        "osx_image": "xcode10.2",
        "language": "node_js",
        "node_js": "10"
      }
    ]
  }
}